apiVersion: v1
kind: Service
metadata:
  name: student-survey-service
spec:
  type: NodePort
  selector:
    app: student-survey
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30036
